Restructuration branche
WildCodeSchool/2023-02-JS-Reims-project-3-inovin pull request #12
Opened 2023-06-06 13:55 UTC by Enzo-adr5

J'ai remis mes branches au propres

2023-06-06 14:41 UTC, Justine-Merlin requested changes

2023-06-06 14:41 UTC, Justine-Merlin commented on frontend/src/components/Note.jsx
Score.jsx ? 😄

2023-06-06 15:12 UTC, Enzo-adr5 commented on frontend/src/components/Note.jsx
c'etait pas comme ca que je devais appeler mon composant ?

2023-06-06 15:15 UTC, Justine-Merlin commented on frontend/src/components/Note.jsx
Il s'appelle Note.jsx actuellement, ce qui correspond pas totalement à ce qu'il y a dedans.

2023-06-07 07:14 UTC, Justine-Merlin approved these changes

2023-06-07 07:15 UTC, merged