Login
WildCodeSchool/2023-02-JS-Reims-project-3-inovin pull request #15
Opened 2023-06-07 12:51 UTC by Enzo-adr5

2023-06-07 12:58 UTC, rocambille requested changes

2023-06-07 12:58 UTC, rocambille commented on package.json
> +    "react-simple-star-rating": "^5.1.7"
these should be installed here : uninstall them

2023-06-07 12:58 UTC, rocambille commented on frontend/src/components/SignIN.jsx
> +function SignIn() {
the file name should follow the name of the component : every letter ;)

2023-06-07 12:58 UTC, rocambille commented on frontend/src/pages/Home.jsx
> +      <SignIn element={SignIn} />
your component has no element prop

2023-06-07 12:58 UTC, rocambille commented on .prettierrc
this file should not be here : remove it

2023-06-07 13:46 UTC, rocambille commented on package.json
> +    "react-simple-star-rating": "^5.1.7"
you still have packages to uninstall ;)

2023-06-07 15:25 UTC, rocambille commented
conflicts to resolve

2023-06-08 09:55 UTC, Justine-Merlin requested changes

2023-06-08 09:55 UTC, Justine-Merlin commented on frontend/src/App.scss
> +.Home {
css class (this is the same for scss) should be write in kebab-case or in camelCase, but not in PascalCase. Rename all of your class.

2023-06-08 09:55 UTC, Justine-Merlin commented on frontend/src/App.scss
> +  .envoie {
Rename it in english.

2023-06-08 09:55 UTC, Justine-Merlin commented on frontend/src/App.scss
> +  .bouton {
Rename it in english.

2023-06-08 09:55 UTC, Justine-Merlin commented on frontend/src/components/SignIn.jsx
> +        <br />
Use css to style and remove this `<br />`

2023-06-08 09:55 UTC, Justine-Merlin commented on frontend/src/contexts/AuthContext.jsx
> +  children: PropTypes.node.isRequired,
`node` prop-type is used to render anything, but in your case that's a React element you want to render. So the correct type is `element` [Documentation](https://legacy.reactjs.org/docs/typechecking-with-proptypes.html#requiring-single-child)

2023-06-08 09:55 UTC, Justine-Merlin commented on package.json
> +  "dependencies": {
Remove these packages from here with `npm rm ...` or `npm uninstall ...`

2023-06-08 10:49 UTC, merged